# Generated by Django 3.2 on 2021-04-27 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password Categories',
            },
        ),
        migrations.CreateModel(
            name='PasswordHint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_belongs_to', models.CharField(max_length=200, verbose_name='Password Relation')),
                ('real_password', models.CharField(max_length=100, verbose_name='Actual Password')),
                ('password_hint_one', models.TextField(verbose_name='First Hint')),
                ('password_hint_two', models.TextField(blank=True, null=True, verbose_name='Second Hint')),
                ('hint_image', models.ImageField(upload_to='hint_image')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('linked_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwords.passwordcategory')),
            ],
            options={
                'verbose_name_plural': 'Password Hints',
            },
        ),
        migrations.CreateModel(
            name='GeneratedPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_belongs_to', models.CharField(max_length=100)),
                ('password_description', models.TextField(blank=True, null=True)),
                ('encrypted_password', models.CharField(max_length=1000)),
                ('security_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Generated Passwords',
            },
        ),
        migrations.CreateModel(
            name='FileEncrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_description', models.CharField(max_length=200, verbose_name='Description of the file')),
                ('actual_file', models.FileField(upload_to='file_uploads')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Encrypted Files',
            },
        ),
    ]
