# Generated by Django 3.2 on 2021-07-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_auto_20210427_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileencrypt',
            name='decrypted_file',
            field=models.FileField(default=None, upload_to='file_uploads'),
        ),
    ]
