# Generated by Django 3.2 on 2021-07-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_fileencrypt_decrypted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileencrypt',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
