# Generated by Django 3.2 on 2021-07-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0004_fileencrypt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileencrypt',
            name='status',
        ),
    ]
